name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      
    - name: Create folders
      run: |
        mkdir -p storage/framework/sessions
        mkdir -p storage/framework/views
        mkdir -p storage/framework/cache
        mkdir -p storage/framework/cache/data
        mkdir -p storage/logs
        
    - name: Fix permissions
      run: |
        sudo chmod -R 775 bootstrap storage/logs
        sudo chmod -R 600 storage
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Create database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Run migrations
      run: php artisan migrate
      
    - name: Install Passport
      run: |
        php artisan passport:keys
        php artisan passport:install
        
    - name: Execute tests
      run: vendor/bin/phpunit
