name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      
    - name: Fix permissions
      run: |
        pwd
        ls -al
        sudo chmod 660 /home/runner/work/rhobooru/rhobooru/storage
        sudo chmod -R 777 /home/runner/work/rhobooru/rhobooru/storage/logs /home/runner/work/rhobooru/rhobooru/storage/framework/cache /home/runner/work/rhobooru/rhobooru/bootstrap/cache
        touch /home/runner/work/rhobooru/rhobooru/storage/logs/test.txt
        touch /home/runner/work/rhobooru/rhobooru/storage/framework/cache/data/test.txt
      
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
        
    - name: Run migrations
      run: php artisan migrate
      
    - name: Install Passport
      run: |
        php artisan passport:keys
        php artisan passport:install
      
    - name: Clear caches
      run: |
        php artisan cache:clear
        php artisan config:clear
        php artisan view:clear
        composer dump-autoload
        
    - name: Execute tests
      run: vendor/bin/phpunit
