name: Test

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: composer install -n --prefer-dist
      
    - name: test
      run: |
        touch storage/logs/test.txt
